// week1 : [{value: 27, rout: []},
//         {value: 28, rout: []},
//         {value: 29, rout: []},
//         {value: 30, rout: []},
//         {value: 31, rout: []},
//         {value: 1, rout: [pointWeekEnd]},
//         {value: 2, rout: [pointAlt, pointAshan, pointAlt]}],

//         week2 : [{value: 3, rout: [pointAlt, pointAshan, pointAlt, pointAshan]},
//         {value: 4, rout: [pointOffice]},
//         {value: 5, rout: [pointAlt, pointAshan, pointAlt]},
//         {value: 6, rout: [pointWeekEnd]},
//         {value: 7, rout: [pointWeekEnd]},
//         {value: 8, rout: []},
//         {value: 9, rout: [pointAlt, pointAshan, pointAlt, pointAshan, pointAlt, pointAshan, pointAlt, pointAshan, pointAlt, pointAshan, pointAlt, pointAshan]}],

//         week3: [{value: 10, rout: [pointAlt, pointAshan, pointAlt]},
//         {value: 11, rout: [pointAlt, pointAshan, pointAlt]},
//         {value: 12, rout: [pointAlt, pointAshan, pointAlt]},
//         {value: 13, rout: [dapointAlt, pointAshan, pointAlt]},
//         {value: 14, rout: []},
//         {value: 15, rout: [pointAtl, pointAshan, pointAlt]},
//         {value: 16, rout: [pointAlt, pointAshan, pointAlt]}],

//         week4: [{value: 17, rout: []},
//         {value: 18, rout: []},
//         {value: 19, rout: []},
//         {value: 20, rout: []},
//         {value: 21, rout: []},
//         {value: 22, rout: []},
//         {value: 23, rout: []}],

//         week5: [{value: 24, rout: [pointAlt, pointAshan, pointAlt]},
//         {value: 25, rout: [pointAlt, pointAshan, pointAlt]},
//         {value: 26, rout: [pointAlt, pointAshan, pointAlt]},
//         {value: 27, rout: [pointAlt, pointAshan, pointAlt]},
//         {value: 28, rout: []},
//         {value: 29, rout: [pointAlt, pointAshan, pointAlt]},
//         {value: 1, rout: [pointAlt, pointAshan, pointAlt]}],

//         pointAlt : { 
//             id: 1, 
//             label: "Чехов-Альттелеком", 
//             name: "205, МЮЗ, ОАО \"Моссковский Ювелирный завод\", г. Химки, Микрорайон Икея, корпус 2", 
//             network: "Белый ветер Цифровой", 
//             endTime: "14:27:15", 
//             endDate: "21.01.2018",
//             address: "143090, Краснознаменск, Молодежная д 2/1"
//             },
//         pointAshan : { 
//           id: 2, 
//           label: "Ашан-Сити-Орехово", 
//           name: "205, МЮЗ, ОАО \"Моссковский Ювелирный завод\", г. Химки, Микрорайон Икея, корпус 2", 
//           network: "Белый ветер Цифровой", 
//           endTime: "14:27:15", 
//           endDate: "21.01.2018", 
//           address: "143090, Краснознаменск, Молодежная д 2/1"
//           },
//         pointWeekEnd : { id: 3, label: "Выходной", name: "", network: "", endTime: "", endDate: "", address: ""},
//         pointOffice : { id: 4, label: "Офис", name: "", network: "", endTime: "", endDate: "", address: ""},
//         pointVacation : { 
//           id: 5, 
//           label: "Отпуск", 
//           name: "", 
//           network: "", 
//           endTime: "", 
//           endDate: "", 
//           address: ""
//           }
//     };
//   },